library_mvc
AleksProkofiev/external-courses pull request #26
Opened 2019-05-26 18:49 UTC by AleksProkofiev

changed the structure of files in accordance with mvc; created objects controller, view, model; refactored individual functions; fixed bugs;

2019-05-27 20:39 UTC, eugrdn requested changes

2019-05-27 20:39 UTC, eugrdn commented on src/library_mvc/src/index.html
> +    <script src="js/utils/first_chat_in_upper_case.js"></script>
у нас тут не python, обычно называют либо через дефис, либо lowerCamelCase

2019-05-27 20:39 UTC, eugrdn commented on src/library_mvc/src/js/app.js
> +    events: function() {
что значит events? это должно быть во view

2019-05-27 20:39 UTC, eugrdn commented on src/library_mvc/src/js/controller.js
> +    model.getFilteredBooks(event, view._renderBooks);
тк модель работает только с данными здесь нужно передать не `event`, а значение

2019-05-27 20:39 UTC, eugrdn commented on src/library_mvc/src/js/controller.js
> +    model.getFilteredBooks(event, view._renderBooks);
ниже в функциях тоже

2019-05-27 20:39 UTC, eugrdn commented on src/library_mvc/src/js/model.js
> +    if (sortedArray.length < 3) {
не понял этого условия

2019-05-27 20:39 UTC, eugrdn commented on src/library_mvc/src/js/model.js
> +    model.getHistoryList(view._renderHistoryList);
модель не знает про view

2019-05-27 20:39 UTC, eugrdn commented on src/library_mvc/src/js/model.js
> +    let dataElem = +event.target.getAttribute("data-elem");
здесь только значение, не event

2019-05-27 20:39 UTC, eugrdn commented on src/library_mvc/src/js/model.js
> +  if (view.$form.elements.title.value !== ""
эту проверку вынеси в контроллер или view, и view здесь быть не должно

2019-05-27 20:39 UTC, eugrdn commented on src/library_mvc/src/js/model.js
> +    book.categories = Array.from(document.querySelectorAll("input.checkbox:checked")).map(function (elem) {
querySelector --> view

2019-05-27 20:39 UTC, eugrdn commented on src/library_mvc/src/js/model.js
> +      let currentTarget = event.target.value || event.target.id ;
только значение, без события

2019-05-27 20:39 UTC, eugrdn commented on src/library_mvc/src/js/model.js
> +  fetchData: function (callback) {
эту функцию лучше вынести в контроллер

2019-05-27 20:39 UTC, eugrdn commented on src/library_mvc/src/js/app.js
> +  let app = {
в методе инициализации нужно сфетчить книги + навесить все обработчики, одно из контроллера, второе из view

2019-05-27 21:52 UTC, AleksProkofiev commented
Согласен с замечаниями. Чтобы написать скрипт строго по паттерну mvc, нужно самую первую строку кода писать по mvc. В моем случае переписать скрипт с нуля будет быстрее и легче, чем заниматься рефакторингом имеющегося. Сейчас пытаюсь создать компоненты через функции-конструкторы по todomvc - появилась проблема с невозможностью вызова метода конструктора, объявленного через prototype в методе такого же типа.  А уже дедлайн.

2019-05-28 08:23 UTC, eugrdn commented
Дедлайн -- понедельник, не считаю, что указанные замечания можно исправить только переписав все заново, и ты же и так сделал этот отдельный PR для задания по mvc? 🙂

2019-05-28 11:50 UTC, AleksProkofiev commented
Да, но это будет уже не то совсем вторник, 28 мая 2019г., 11:23 +03:00 от Eugene Rodin  notifications@github.com :

>Дедлайн -- понедельник, не считаю, что указанные замечания можно исправить только переписав все заново, и ты же и так сделал этот отдельный PR для задания по mvc? 🙂
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

2019-05-30 21:10 UTC, AleksProkofiev commented
Поправил все

2019-05-31 13:45 UTC, eugrdn commented on src/library_mvc/src/js/model.js
> +  let book = {
почему не сращу проверить элемент через `if`?

2019-05-31 13:52 UTC, eugrdn requested changes

2019-05-31 13:52 UTC, eugrdn commented on src/library_mvc/src/js/controller.js
> +      this.dispatcherHistory("addBook", [temp.title, temp.author.firstName, temp.author.lastName]);
`dispatchToHistory`

2019-05-31 13:52 UTC, eugrdn commented on src/library_mvc/src/js/controller.js
> +  if (event.target.classList.contains("rating_star")) {
`event` это сущность для view

2019-05-31 13:52 UTC, eugrdn commented on src/library_mvc/src/js/app.js
> +    this.view.$closePopUp.addEventListener("click", () => {
почему это не во view

2019-05-31 13:52 UTC, eugrdn commented on src/library_mvc/src/js/model.js
> +  this.flag = false;
так лучше никогда не делать

2019-05-31 13:52 UTC, eugrdn commented on src/library_mvc/src/js/model.js
> +  this.state = [];
что значит state=[]? у тебя state'ом должны быть книги, история, строка поиска и выбранный фильтр

2019-05-31 13:52 UTC, eugrdn commented on src/library_mvc/src/js/model.js
> +  for (let i = 0; i < this.books.length; i++) {
.find

2019-05-31 13:52 UTC, eugrdn commented on src/library_mvc/src/js/app.js
> +    this.view.$addBookBtn.addEventListener("click", () => {
передавай в контроллер не event, а значение

2019-05-31 13:52 UTC, eugrdn commented on src/library_mvc/src/js/app.js
> +    },500));
500 в константу

2019-05-31 23:31 UTC, AleksProkofiev commented
все изменения перечислил в commit-massage

2019-06-02 14:04 UTC, eugrdn commented on src/library_mvc/src/js/model.js
> +  let requiredBook = this.books.findIndex((elem) => {
`let requiredBook = this.books.find((elem) => elem.id === id)
requiredBook[property] = value;`

2019-06-02 14:05 UTC, merged